title: 表格数据
type: community
group: 结构化数据解析
image: /static/templates/tabular-data.png
details: <h1>Annotate data in tables</h1>
config: '
<View>
    <Header value="Table with {key: value} pairs"/>
    <Table name="table" value="$item"/>
</View>
'
